name: Daily Build and Deploy

on:
  schedule:
    # Runs every day at 2 AM UTC (adjust timezone as needed)
    - cron: '0 2 * * *'
  workflow_dispatch: # Allows manual triggering
  push:
    branches: [ main ]
    paths:
      - 'build.js'
      - 'serverBuilder.js'
      - 'package.json'
      - 'static/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build site
      env:
        WP_API_URL: ${{ secrets.WP_API_URL }}
        BUILD_DIR: build
        TEMPLATES_DIR: static/templates
      run: npm run build
      
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push if changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Automated daily build - $(date '+%Y-%m-%d %H:%M:%S')"
        git push
        
    - name: Display build status
      run: |
        if [[ "${{ steps.verify-changed-files.outputs.changed }}" == "true" ]]; then
          echo "✅ Changes detected and committed"
        else
          echo "ℹ️ No changes detected"
        fi 